In [1]:
#Map Function, Filter Function

def square(n): #for square
    return n*n
def even(n): #for even
    return n%2==0 #return n%2==0 mane hocche true naki false return kora true return korle even number print korbe

list_1=[1,2,3,4,5,6,7,8,9,10]

square = list(map(square,list_1))
print(square)

even_number = list(map(even,list_1)) #Set diyeo hobe but apatoto hocchena
print(even_number)

even_number_filter = list(filter(even,list_1))
print(even_number_filter)

odd_number_filter = list(filter(lambda n: n%2!=0, list_1))
print(odd_number_filter)

for i in list_1:
    print(i*i, end=" ")

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[False, True, False, True, False, True, False, True, False, True]
[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]
1 4 9 16 25 36 49 64 81 100 

In [2]:
def odd(a):
    if a%2==1:
        return True
    else:
        return False #else part is optional here. just for completion
list_2=[1,2,3,4,5,6,7]
odd_numbers = filter(odd,list_2)
list(odd_numbers) #If it returns true it will print the odd numbers


[1, 3, 5, 7]

In [3]:
#Numpy
l=[1,2,3,4] #One dimensional array
l

[1, 2, 3, 4]

In [4]:
l1=[[1,1],[2,2],[3,3],[4,4]]
l1 #two dimensional arrray

[[1, 1], [2, 2], [3, 3], [4, 4]]

In [5]:
l2=[[1,1,1],[2,2,2],[3,3,3],[4,4,4]]
l2 #three dimensional array

[[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]

In [6]:
import numpy as np #np hocche choddo nam. numpy lekha tough bole np lekha

In [7]:
np_arr = np.array(l1)
np_arr

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [8]:
type(l1), type(np_arr)

(list, numpy.ndarray)

In [9]:
ls1=[1,2,3,4]
ls2=[3,4,5,6]
ls3=[5,9,8,7]
merged = np.array([ls1,ls2,ls3]) #onekgula array rakhar khetre third bracket use korte hobe
merged

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 9, 8, 7]])

In [10]:
merged.shape #3 rows, 4 columns

(3, 4)

In [11]:
type(merged)

numpy.ndarray

In [12]:
merged[0] #pura row tai  ekta element ekhane

array([1, 2, 3, 4])

In [13]:
merged[0][0]

1

In [14]:
merged[1][2]

5

In [15]:
merged[1][3]

6

In [16]:
merged[1:]

array([[3, 4, 5, 6],
       [5, 9, 8, 7]])

In [17]:
merged[:1]

array([[1, 2, 3, 4]])

In [18]:
merged[:2]

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [19]:
merged[:0]

array([], shape=(0, 4), dtype=int32)

In [20]:
merged[:2][1:] #first e 0 and 1 number row print hoise. erpor oi array er vitore 1: operate korse mane 1 number row ta print hoise 

array([[3, 4, 5, 6]])

In [21]:
merged[2:][0:]

array([[5, 9, 8, 7]])

In [22]:
merged[0:][2:]

array([[5, 9, 8, 7]])

In [23]:
#basically comma diye row, column print kore 'slicing' korte hoy
merged[2:,1:] #merged[row:,column:]

array([[9, 8, 7]])

In [24]:
np.arange(5,20) #single dimensional array create korar jonno 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.zeros((2,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.random.rand(2,3)

array([[0.67570716, 0.08088783, 0.77120013],
       [0.68810461, 0.8975763 , 0.63028046]])

In [28]:
np.random.randint(2,3)

2

In [29]:
n=np.arange(5,15)
n

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
n.reshape(5,2) #Row and column er gunfol elements er soman hote hobe

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [31]:
#Generating integer number --------Problem
for i in range(10):
    value = randint(0,20) #0 is the lower limit and 20 is the upper limit
    print(value)

NameError: name 'randint' is not defined

In [ ]:
#Pandas

In [32]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.arange(0,30).reshape(5,6),index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4','C5','C6'])
df

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [33]:
df.values

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
df.values[4][5]

29

In [35]:
df.head(3) # head() returns first 5 values of row for default values

C1  C2  C3  C4  C5  C6
R1   0   1   2   3   4   5
R2   6   7   8   9  10  11
R3  12  13  14  15  16  17

In [36]:
df.tail(3)

C1  C2  C3  C4  C5  C6
R3  12  13  14  15  16  17
R4  18  19  20  21  22  23
R5  24  25  26  27  28  29

In [37]:
list(df.columns)

['C1', 'C2', 'C3', 'C4', 'C5', 'C6']

In [38]:
list(df.index)

['R1', 'R2', 'R3', 'R4', 'R5']

In [39]:
df_list=list(df.columns.values)
df_list

['C1', 'C2', 'C3', 'C4', 'C5', 'C6']

In [40]:
sorted(df_list, reverse=True)

['C6', 'C5', 'C4', 'C3', 'C2', 'C1']

In [41]:
df.loc[:,'C2'] #columns

R1     1
R2     7
R3    13
R4    19
R5    25
Name: C2, dtype: int32

In [42]:
df.loc['R3'] #rows

C1    12
C2    13
C3    14
C4    15
C5    16
C6    17
Name: R3, dtype: int32

In [43]:
df.iloc[2]

C1    12
C2    13
C3    14
C4    15
C5    16
C6    17
Name: R3, dtype: int32

In [44]:
df.iloc[:2,:3] #slicing korar somoy row,column pashapashi comma diye likhte hoy

C1  C2  C3
R1   0   1   2
R2   6   7   8

In [45]:
df_mb = pd.read_csv("D:\DS-ML-Bootcamp/mercedesbenz.csv")
df_mb.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379   
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0  \
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [46]:
df_mb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [47]:
df_mb.shape

(4209, 378)

In [48]:
df_mb.describe() #protita datar mean, standard deviation, max, min etc. dekhar jonno

ID            y          X10     X11          X12   
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000  \
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...   
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...  \
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379   
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  \
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [49]:
df_mb['y']


0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [50]:
df_mb['y'][0]

130.81

In [51]:
df_mb['y']>200

0       False
1       False
2       False
3       False
4       False
        ...  
4204    False
4205    False
4206    False
4207    False
4208    False
Name: y, Length: 4209, dtype: bool

In [52]:
df_mb[df_mb['y']>150] #y column e jekhane jekhane 150 er uporer value ache sei value related row er sob information dekhabe

ID       y  X0  X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378   
253    505  150.43   t   b  as  c  d   i  l  x  ...     0     0     1     0  \
342    681  169.91  aa   l  ak  f  d   i  c  d  ...     0     0     0     0   
429    836  154.87  ak   l  ae  f  d   d  g  w  ...     0     0     0     0   
883   1770  265.32   y   r  ai  f  d  ag  l  t  ...     0     0     0     0   
889   1784  158.53  aj   l  as  f  d  ag  k  e  ...     0     0     0     0   
1060  2111  154.43   w   v   r  c  d  ag  d  q  ...     1     0     0     0   
1203  2396  160.87   j   o  as  f  d  ab  g  p  ...     1     0     0     0   
1205  2403  150.89   x   b   m  c  d  ab  j  j  ...     0     0     1     0   
1269  2511  152.32   s  aa   m  c  d  ab  g  g  ...     1     0     0     0   
1459  2903  167.45  ai   b  ae  a  d  ac  g  m  ...     0     0     1     0   
2240  4481  154.16   w   n  as  f  d   k  j  r  ...     1     0     0     0   
2735  5471  158.23   x   v   e  c  d   m  g  s  ...     0     0     0     0   
2736  5473  153.51   x   i  as  a  d   m  j  r  ...     0     0     1     0   
3133  6273  165.52  aj   v   r  c  d   q  g  a  ...     0     0     1     0   
3744  7500  155.62   x   f  ak  c  d   v  d  d  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
253      0     0     0     1     0     0  
342      0     0     0     0     0     0  
429      0     0     0     0     0     0  
883      0     0     0     0     0     0  
889      0     0     0     0     0     0  
1060     0     0     0     0     0     0  
1203     0     0     0     0     0     0  
1205     0     0     0     0     0     0  
1269     0     0     0     0     0     0  
1459     0     0     0     0     0     0  
2240     0     0     0     0     0     0  
2735     1     0     0     0     0     0  
2736     0     0     0     0     0     0  
3133     0     0     0     0     0     0  
3744     0     0     0     0     0     0  

[15 rows x 378 columns]

### Problem-1 Can't find the Correlation

In [59]:
df_mb.corr()
 

ValueError: could not convert string to float: 'k'

### Problem-2 Can't read csv file directly from link


In [68]:
df = pd.read_csv("https://download.bls.gov/pub/time.series/cu/cu.item", sep='\t')
df.head()
#error ashar kotha na but kono karone kaj hocchena

HTTPError: HTTP Error 403: Forbidden

In [62]:
#Solution-1 from google
url = 'https://download.bls.gov/pub/time.series/cu/cu.item'
storage_options = {'User-Agent': 'Mozilla/5.0'}
df = pd.read_csv(url, storage_options=storage_options)

HTTPError: HTTP Error 403: Forbidden

In [64]:
#Solution-2 from google
import pandas as pd

from urllib.request import Request, urlopen  # Python 3


req = Request('https://download.bls.gov/pub/time.series/cu/cu.item')
req.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36')
content = urlopen(req)

df = pd.read_csv(content)
print(df)

HTTPError: HTTP Error 403: Forbidden

In [66]:
#JSON,HTML,Pickle

In [79]:
data='{"Name":"Jamee","Age":"18","email":"jamee.islam2018@gmail.com","Job Profile":[{"Titile1":"Team Lead","Title2":"Developer"}]}'
pd.read_json(data)

Name  Age                      email   
0  Jamee   18  jamee.islam2018@gmail.com  \

                                       Job Profile  
0  {'Titile1': 'Team Lead', 'Title2': 'Developer'}

In [87]:
wine = pd.read_csv("D:\DS-ML-Bootcamp/wine.data", header=None)
wine.head()

0      1     2     3     4    5     6     7     8     9     10    11    12   
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92  \
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [95]:
wine.to_csv("D:\DS-ML-Bootcamp/wine.csv") 

In [96]:
wine.to_json(orient="records") #First e column, then value access

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"

In [97]:
wine.to_json(orient="index") #First e index, then column, then value

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [101]:
read_excel=pd.read_excel("D:\DS-ML-Bootcamp/Excel_Sample.xlsx")
read_excel.head() #openpyxl install dewar por

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [102]:
#Pickling

In [104]:
read_excel.to_pickle("D:\DS-ML-Bootcamp/Excel.pickle")

In [105]:
pickle=pd.read_pickle("D:\DS-ML-Bootcamp/Excel.pickle")
pickle.head()

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15